# Generated by Django 5.1.3 on 2024-11-29 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_customimage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="_privacy",
            field=models.CharField(default="public", max_length=10),
        ),
        migrations.AddField(
            model_name="customimage",
            name="file_permissions_last_set",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="customimage",
            name="privacy_last_changed",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
