# Generated by Django 5.1.3 on 2024-11-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_remove_customimage_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
