# Generated by Django 5.1.3 on 2024-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_customdocument__privacy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdocument",
            name="_privacy",
            field=models.CharField(default="private", max_length=10),
        ),
    ]
