# Generated by Django 5.2.3 on 2025-08-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("organisation", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=120)),
            ],
        ),
    ]
