# Generated by Django 5.2.3 on 2025-08-13 08:33
from time import sleep

from django.db import migrations, models


def pause_forward(apps, schema_editor):
    # Slow migration
    sleep(5)


def pause_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(pause_forward, pause_reverse),
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
