# Generated by Django 5.1.2 on 2024-10-28 16:51

import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactDetails",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "contact details",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
