# Generated by Django 5.1.3 on 2024-11-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
