# Generated by Django 5.1.4 on 2024-12-10 11:08
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_tracking"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contactdetails",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                django.db.models.functions.text.Lower("email"),
                name="core_contactdetails_name_unique",
                violation_error_message="Contact details with this name and email combination already exists.",
            ),
        ),
    ]
