# Generated by Django 5.1.4 on 2024-12-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdetails",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
