# Generated by Django 5.1.4 on 2024-12-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_tracking"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contactdetails",
            constraint=models.UniqueConstraint(fields=("name", "email"), name="core_contactdetails_name_unique"),
        ),
    ]
