# Generated by Django 5.1.6 on 2025-03-03 16:20

import django.db.models.deletion
import django.db.models.functions.text
import wagtail.fields
import wagtail.search.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_contactdetails_core_contactdetails_name_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("definition", wagtail.fields.RichTextField()),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glossary_terms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Glossary terms",
                "verbose_name_plural": "Glossary terms",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("title"),
                        name="core_glossary_term_title_unique",
                        violation_error_message="A glossary term with this title already exists.",
                    )
                ],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
