# Generated by Django 5.1.7 on 2025-04-02 12:40

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_glossaryterm"),
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="glossaryterm",
            name="core_glossary_term_name_unique",
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="expired",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="first_published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="go_live_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="has_unpublished_changes",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="last_published_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="live",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name="glossaryterm",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="glossaryterm",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("locale"),
                name="core_glossary_term_name_unique",
                violation_error_message="A glossary term with this name for this locale already exists.",
            ),
        ),
    ]
