# Generated by Django 5.1.7 on 2025-04-04 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_update_user_groups"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="glossaryterm",
            name="core_glossary_term_name_unique",
        ),
        migrations.RemoveConstraint(
            model_name="glossaryterm",
            name="unique_translation_key_locale_core_glossaryterm",
        ),
        migrations.AlterUniqueTogether(
            name="glossaryterm",
            unique_together={("name", "locale"), ("translation_key", "locale")},
        ),
    ]
