# Generated by Django 5.2.3 on 2025-07-16 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_glossaryterm_core_glossary_term_name_unique_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SystemMessagesSettings",
        ),
    ]
