# Generated by Django 5.1.7 on 2025-04-08 13:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_bootstrap_translatable_model"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contactdetails",
            name="core_contactdetails_name_unique",
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="locale",
            field=models.ForeignKey(
                editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale"
            ),
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="contactdetails",
            unique_together={("name", "email", "locale"), ("translation_key", "locale")},
        ),
    ]
