# Generated by Django 5.1.7 on 2025-04-09 14:57

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_bootstrap_translatable_model"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contactdetails",
            name="core_contactdetails_name_unique",
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="locale",
            field=models.ForeignKey(
                editable=False, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="wagtailcore.locale"
            ),
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="contactdetails",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AddConstraint(
            model_name="contactdetails",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                django.db.models.functions.text.Lower("email"),
                models.F("locale"),
                name="core_contactdetails_name_unique",
                violation_error_message="Contact details with this name and email combination already exists.",
            ),
        ),
    ]
