# Generated by Django 5.2.9 on 2026-02-02 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_publishing_officers_publish_permission(apps, schema_editor):
    """Grant the publish permission for ContactDetails and Definition."""
    ContentType = apps.get_model("contenttypes.ContentType")
    Group = apps.get_model("auth.Group")
    Permission = apps.get_model("auth.Permission")

    group = Group.objects.get(name=settings.PUBLISHING_ADMINS_GROUP_NAME)
    snippet_classes = [
        ("core.ContactDetails", "publish_contactdetails"),
        ("core.Definition", "publish_definition"),
    ]

    for app_label, permission_codename in snippet_classes:
        model_class = apps.get_model(app_label)
        permission, _was_created = Permission.objects.get_or_create(
            content_type=ContentType.objects.get_for_model(model_class),
            codename=permission_codename,
            defaults={"name": f"Can {' '.join(permission_codename.split('_'))}"},
        )

        group.permissions.add(permission)


def remove_publishing_officers_publish_permission(apps, schema_editor):
    """Remove the publish permission for ContactDetails and Definition."""
    Group = apps.get_model("auth.Group")
    Permission = apps.get_model("auth.Permission")

    group = Group.objects.get(name=settings.PUBLISHING_OFFICERS_GROUP_NAME)
    group.permissions.remove(Permission.objects.get(codename="publish_definition"))
    group.permissions.remove(Permission.objects.get(codename="publish_contactdetails"))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_migrate_imageblock_caption"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdetails",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="expired",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="first_published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="go_live_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="has_unpublished_changes",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="last_published_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
            ),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="live",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name="contactdetails",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
            ),
        ),
        migrations.AddField(
            model_name="definition",
            name="expire_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="definition",
            name="expired",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="definition",
            name="first_published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="definition",
            name="go_live_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="definition",
            name="has_unpublished_changes",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="definition",
            name="last_published_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="definition",
            name="live",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name="definition",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
            ),
        ),
        # and finally, grant the necessary permissions
        migrations.RunPython(add_publishing_officers_publish_permission, remove_publishing_officers_publish_permission),
    ]
