# Generated by Django 5.2.12 on 2026-04-09 13:49

from django.db import migrations


def delete_existing_page_view_restrictions(apps, schema_editor):
    """Delete all existing page view restrictions."""
    PageViewRestriction = apps.get_model("wagtailcore.PageViewRestriction")
    PageViewRestriction.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_allow_officers_to_lock"),
    ]

    operations = [
        migrations.RunPython(delete_existing_page_view_restrictions, reverse_code=migrations.RunPython.noop),
    ]
