# Generated by Django 5.1.2 on 2024-11-06 14:12

from django.db import migrations

import cms.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("release_calendar", "0002_create_releasecalendarindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="releasecalendarpage",
            name="related_links",
            field=cms.core.fields.StreamField(blank=True, block_lookup={}),
        ),
        migrations.DeleteModel(
            name="ReleasePageRelatedLink",
        ),
    ]
