# Generated by Django 5.1.8 on 2025-04-30 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("release_calendar", "0003_releasecalendarpage_datasets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="releasecalendarpage",
            old_name="next_release_text",
            new_name="next_release_date_text",
        ),
        migrations.AlterField(
            model_name="releasecalendarpage",
            name="release_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
