# Generated by Django 5.1.8 on 2025-04-15 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("release_calendar", "0003_releasecalendarpage_datasets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="releasecalendarpage",
            old_name="next_release_text",
            new_name="next_release_date_text",
        ),
    ]
