# Generated by Django 5.1.8 on 2025-05-19 16:51

from django.db import migrations, models

import cms.core.custom_date_format


class Migration(migrations.Migration):
    dependencies = [
        ("release_calendar", "0004_make_release_date_mandatory_and_rename_next_release_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasecalendarpage",
            name="release_date",
            field=models.DateTimeField(default=cms.core.custom_date_format.ons_default_datetime),
        ),
    ]
