# Generated by Django 5.2.3 on 2025-06-24 11:21

from django.db import migrations, models

import cms.core.custom_date_format


class Migration(migrations.Migration):
    dependencies = [
        ("release_calendar", "0005_add_notice_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releasecalendarpage",
            name="release_date",
            field=models.DateTimeField(default=cms.core.custom_date_format.ons_default_datetime),
        ),
    ]
