# Generated by Django 6.0.8 on 2026-09-03 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RenderedChartImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ("_privacy", models.CharField(default="private", max_length=10)),
                ("file_permissions_last_set", models.DateTimeField(editable=False, null=True)),
                ("privacy_last_changed", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("file", models.FileField()),
                ("export_id", models.UUIDField(unique=True)),
                ("config_hash", models.CharField(db_index=True, max_length=64)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
