# Generated by Django 5.1.4 on 2025-01-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datavis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="column_count",
            field=models.IntegerField(editable=False, default=0),
        ),
    ]
