# Generated by Django 5.1.4 on 2025-01-17 20:17

from django.db import migrations

import cms.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("datavis", "0003_chart_marker_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="annotations",
            field=cms.core.fields.StreamField(blank=True, block_lookup={}, default=[]),
        ),
        migrations.DeleteModel(
            name="Annotation",
        ),
    ]
