# Generated by Django 5.1.4 on 2025-01-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datavis", "0004_chart_annotations_delete_annotation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chart",
            name="legend_position",
        ),
        migrations.AlterField(
            model_name="chart",
            name="show_legend",
            field=models.BooleanField(default=True),
        ),
    ]
