# Generated by Django 5.1.4 on 2025-01-27 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datavis", "0005_remove_chart_legend_position_alter_chart_show_legend"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScatterChart",
            fields=[],
            options={
                "verbose_name": "statter chart",
                "verbose_name_plural": "statter charts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("datavis.chart",),
        ),
    ]
