# Generated by Django 5.1.4 on 2025-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datavis", "0006_scatterchart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionaldatasource",
            name="data_source",
        ),
        migrations.RemoveField(
            model_name="additionaldatasource",
            name="visualisation",
        ),
        migrations.RemoveField(
            model_name="chart",
            name="visualisation_ptr",
        ),
        migrations.RemoveField(
            model_name="datasource",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="datasource",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="visualisation",
            name="primary_data_source",
        ),
        migrations.RemoveField(
            model_name="visualisation",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="visualisation",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="visualisation",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="AreaChart",
        ),
        migrations.DeleteModel(
            name="BarChart",
        ),
        migrations.DeleteModel(
            name="ColumnChart",
        ),
        migrations.DeleteModel(
            name="LineChart",
        ),
        migrations.DeleteModel(
            name="ScatterChart",
        ),
        migrations.DeleteModel(
            name="AdditionalDataSource",
        ),
        migrations.DeleteModel(
            name="Chart",
        ),
        migrations.DeleteModel(
            name="DataSource",
        ),
        migrations.DeleteModel(
            name="Visualisation",
        ),
    ]
