---
# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

FORMATTERS_DISABLE_ERRORS: false

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE:
  - COPYPASTE
  - PYTHON
  - JAVASCRIPT
  - EDITORCONFIG
  - SPELL

# REPOSITORY_TRIVY, REPOSITORY_DUSTILOCK, HTML_HTMLHINT Have been disabled as part of the initial set up
# CMS_
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_GIT_DIFF
  - HTML_HTMLHINT
  - REPOSITORY_TRIVY
  - REPOSITORY_DUSTILOCK

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

# Use yml file to allow the use of comments. Megalinter's default is .markdown-lint.json
CSS_STYLELINT_CONFIG_FILE: .github/linters/.stylelintrc.js
DOCKERFILE_HADOLINT_CONFIG_FILE: .github/linters/.hadolint.yaml
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .github/linters/.markdown-lint.yml
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: .github/linters/.markdown-link-check.json
REPOSITORY_CHECKOV_CONFIG_FILE: .github/linters/.checkov.yml
REPOSITORY_GITLEAKS_CONFIG_FILE: .github/linters/.gitleaks.toml
REPOSITORY_GITLEAKS_ARGUMENTS: ['protect .']
REPOSITORY_GRYPE_CONFIG_FILE: .github/linters/.grype.yaml
REPOSITORY_KICS_CONFIG_FILE: .github/linters/kics.config
YAML_YAMLLINT_CONFIG_FILE: .github/linters/.yaml-lint.yml

YAML_V8R_FILTER_REGEX_EXCLUDE:
  'dependabot.yml' # Dependabot yaml in SchemaStore is currently not up to date.
  # Dependabot is validated on push by GitHub by default.

EXCLUDED_DIRECTORIES: ['node_modules', 'static', 'static_compile']
