# See https://prettier.io/docs/en/options.html.
# Prettier also reads .editorconfig.
printWidth = 100
singleQuote = true
quoteProps = 'consistent'
trailingComma = 'all'
arrowParens = 'always'
proseWrap = 'preserve'
