---
###########################################
# These are the rules used for            #
# linting all the yaml files in the stack #
# NOTE:                                   #
# You can disable line with:              #
# # yamllint disable-line                 #
###########################################
extends: default
rules:
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
