# Generated by Django 5.1.8 on 2025-05-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bundles", "0002_bundleteam"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundleteam",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
