# Generated by Django 5.1.9 on 2025-06-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bundles", "0003_bundledataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundleteam",
            name="preview_notification_sent",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
