# Generated by Django 5.2.3 on 2025-07-17 11:04
import django.utils.timezone
from django.db import migrations, models
from django.db.models.functions import Cast


def update_bundles_updated_at(apps, schema_editor):
    Bundle = apps.get_model("bundles", "Bundle")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ModelLogEntry = apps.get_model("wagtailcore", "ModelLogEntry")

    latest_log = (
        ModelLogEntry.objects.filter(
            content_type=ContentType.objects.get_for_model(Bundle, for_concrete_model=False).pk,
            object_id=Cast(models.OuterRef("pk"), models.CharField()),
        )
        .order_by("-timestamp", "-pk")
        .values("timestamp")[:1]
    )
    for bundle in Bundle.objects.annotate(_updated_at=models.Subquery(latest_log)):
        bundle.updated_at = bundle._updated_at
        bundle.save(update_fields=["updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("bundles", "0004_bundleteam_preview_notification_sent"),
    ]

    operations = [
        # first add the field with a default value
        migrations.AddField(
            model_name="bundle",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        # populate from log entry data. No need for a reverse action.
        migrations.RunPython(update_bundles_updated_at, reverse_code=migrations.RunPython.noop),
        # finally, update it so it uses auto now.
        migrations.AlterField(
            model_name="bundle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
