# Generated by Django 5.2.3 on 2025-07-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0004_bundleteam_preview_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='bundle_api_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bundledataset',
            name='content_api_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
