# Generated by Django 5.2.3 on 2025-07-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bundles", "0005_bundle_bundle_api_id"),
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundledataset",
            name="content_api_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="bundledataset",
            unique_together={("parent", "dataset")},
        ),
    ]
