# Generated by Django 5.2.7 on 2025-11-02 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bundles", "0006_bundle_bundle_api_id_bundledataset_content_api_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bundle",
            old_name="bundle_api_content_id",
            new_name="bundle_api_bundle_id",
        ),
    ]
