# Generated by Django 5.2.12 on 2026-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bundles", "0007_rename_bundle_api_content_id_bundle_bundle_api_bundle_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="slack_notification_ts",
            field=models.CharField(blank=True, db_default="", editable=False, max_length=32),
        ),
    ]
