---
# https://github.com/bridgecrewio/checkov
compact: true
download-external-modules: false
evaluate-variables: true
output: cli
quiet: true
soft-fail: false
skip-check:
  # Ensure top-level permissions are not set to write-all
  - CKV2_GHA_1
  # Ensure that sudo isn't used
  - CKV2_DOCKER_1
  # Ensure that APT isn’t used
  - CKV_DOCKER_9
  # Ensure that HEALTHCHECK instructions have been added to container images
  - CKV_DOCKER_2
summary-position: bottom
