# Generated by Django 5.1.5 on 2025-01-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0003_alter_genericpagetotaxonomytopic_unique_together_and_more"),
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="themepage",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_%(class)s",
                to="taxonomy.topic",
            ),
        ),
    ]
