# Generated by Django 6.0.8 on 2026-09-14 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0004_alter_genericpagetotaxonomytopic_topic"),
        ("themes", "0003_themeindexpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="themepage",
            name="topic",
            field=models.ForeignKey(
                limit_choices_to={"depth__gt": 1},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_%(class)s",
                to="taxonomy.topic",
            ),
        ),
    ]
