# Generated by Django 6.0.6 on 2026-06-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bundles", "0008_bundle_slack_notification_ts"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostPublishAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("action_type", models.CharField(max_length=14)),
                ("status", models.CharField(default="READY", max_length=10)),
                ("failed_reason", models.TextField(default="")),
                ("enqueued_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.DurationField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("timed_out_at", models.DateTimeField(null=True)),
                (
                    "bundle",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="bundles.bundle"),
                ),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.page")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("bundle__isnull", False)),
                        fields=("bundle", "page", "action_type"),
                        name="bundle_page_type",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("bundle", None)), fields=("page", "action_type"), name="page_type"
                    ),
                ],
            },
        ),
    ]
