# Generated by Django 5.1.6 on 2025-02-19 09:55

from django.db import migrations

import cms.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0003_topicpage_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="headline_figures",
            field=cms.core.fields.StreamField(blank=True, block_lookup={}),
        ),
    ]
