# Generated by Django 5.1.8 on 2025-05-02 10:24

from django.db import migrations


def rename_headline_figures_type(apps, schema_editor, new_name):
    TopicPage = apps.get_model("topics", "TopicPage")

    # Migrate the headline figures from the old field to the new field
    for topic_page in TopicPage.objects.all():
        if topic_page.headline_figures:
            for entry in topic_page.headline_figures.raw_data:
                entry["type"] = new_name
            topic_page.save(update_fields=["headline_figures"])


def migrate_topic_figures(apps, schema_editor):
    rename_headline_figures_type(apps, schema_editor, "figure")


def reverse_migrate_topic_figures(apps, schema_editor):
    rename_headline_figures_type(apps, schema_editor, "figures")


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0004_topicpage_headline_figures"),
    ]

    operations = [
        migrations.RunPython(migrate_topic_figures, reverse_code=reverse_migrate_topic_figures),
    ]
