# Generated by Django 5.1.8 on 2025-05-02 10:24

import json

from django.db import migrations


def rename_headline_figures_type(apps, schema_editor, new_name):
    TopicPage = apps.get_model("topics", "TopicPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    ContentType = apps.get_model("contenttypes", "ContentType")

    topic_page_content_type = ContentType.objects.get_for_model(TopicPage)

    # Migrate the headline figures from the old field to the new field
    for topic_page in TopicPage.objects.all():
        if topic_page.headline_figures:
            for entry in topic_page.headline_figures.raw_data:
                entry["type"] = new_name
            topic_page.save(update_fields=["headline_figures"])

    # Update the revisions
    revisions_to_update = Revision.objects.filter(content_type=topic_page_content_type).iterator()

    for revision in revisions_to_update:
        if headline_figures_json := revision.content.get("headline_figures"):
            headline_figures = json.loads(headline_figures_json)
            for entry in headline_figures:
                entry["type"] = new_name
            revision.content["headline_figures"] = json.dumps(headline_figures)
            revision.save(update_fields=["content"])


def migrate_topic_figures(apps, schema_editor):
    rename_headline_figures_type(apps, schema_editor, "figure")


def reverse_migrate_topic_figures(apps, schema_editor):
    rename_headline_figures_type(apps, schema_editor, "figures")


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0004_topicpage_headline_figures"),
    ]

    operations = [
        migrations.RunPython(migrate_topic_figures, reverse_code=reverse_migrate_topic_figures),
    ]
