# Generated by Django 5.2.3 on 2025-07-28 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0006_topicpage_datasets"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpagerelatedarticle",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedarticle",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedarticle",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="topicpagerelatedarticle",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
