# Generated by Django 5.2.3 on 2025-08-06 11:56

from django.db import migrations

import cms.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0007_topicpagerelatedarticle_external_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="time_series",
            field=cms.core.fields.StreamField(blank=True, block_lookup={}, default=list),
        ),
    ]
