# Generated by Django 5.2.13 on 2026-05-05 14:10

import django.db.models.deletion
from django.db import migrations, models


def cleanup_on_rollback(apps, schema_editor):
    # previous version required a related page, so delete any entries that don't have one to avoid integrity errors
    TopicPageRelatedMethodology = apps.get_model("topics", "TopicPageRelatedMethodology")  # pylint: disable=C0103
    TopicPageRelatedMethodology.objects.filter(page=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0008_topicpage_time_series"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpagerelatedmethodology",
            name="content_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedmethodology",
            name="description",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedmethodology",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedmethodology",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedmethodology",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="topicpagerelatedmethodology",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, cleanup_on_rollback),
    ]
