# Generated by Django 5.2.13 on 2026-04-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0008_topicpage_time_series"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpagerelatedmethodology",
            name="content_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedmethodology",
            name="external_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedmethodology",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="topicpagerelatedmethodology",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
