# Generated by Django 6.0.5 on 2026-05-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0008_topicpage_time_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpagerelatedarticle",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="topicpagerelatedarticle",
            name="description",
            default="",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedarticle",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
