# Generated by Django 6.0.5 on 2026-05-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topics", "0009_topicpagerelatedmethodology_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpagerelatedarticle",
            name="content_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedarticle",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topicpagerelatedarticle",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
