# Generated by Django 5.1.2 on 2024-11-07 13:17

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(max_length=255, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('rich_text', 1), ('panel', 5), ('embed', 6), ('image', 7), ('documents', 12), ('related_links', 13), ('equation', 14), ('ons_embed', 17)], block_lookup={0: ('cms.core.blocks.markup.HeadingBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('announcement', 'Announcement'), ('bare', 'Bare'), ('branded', 'Branded'), ('error', 'Error'), ('ghost', 'Ghost'), ('success', 'Success'), ('warn-branded', 'Warn (branded)'), ('warn', 'Warn')]}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link']}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Title (optional)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('variant', 2), ('body', 3), ('title', 4)]], {}), 6: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('document', 8), ('title', 9), ('description', 10)]], {}), 12: ('wagtail.blocks.StreamBlock', [[('document', 11)]], {}), 13: ('cms.core.blocks.related.RelatedLinksBlock', (wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.blocks.URLBlock(label='or External Link', required=False)), ('title', wagtail.blocks.CharBlock(help_text="Populate when adding an external link. When choosing a page, you can leave it blank to use the page's own title", required=False)), ('description', wagtail.blocks.CharBlock(required=False))]),), {}), 14: ('wagtailmath.blocks.MathBlock', (), {'group': 'DataVis', 'icon': 'decimal'}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'Must start with <code>https://www.ons.gov.uk/visualisations/</code> to your URL.'}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Interactive chart'}), 17: ('wagtail.blocks.StructBlock', [[('url', 15), ('title', 16)]], {'group': 'DataVis', 'label': 'ONS General Embed'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
