# Generated by Django 5.1.2 on 2024-11-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationpage',
            old_name='body',
            new_name='content',
        ),
    ]
