# Generated by Django 5.1.5 on 2025-01-29 13:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import cms.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0004_alter_customimage__privacy"),
        ("standard_pages", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("listing_title", models.CharField(blank=True, max_length=255)),
                ("listing_summary", models.CharField(blank=True, max_length=255)),
                ("social_text", models.CharField(blank=True, max_length=255)),
                ("summary", wagtail.fields.RichTextField()),
                ("featured_items", cms.core.fields.StreamField(blank=True, block_lookup={})),
                ("content", wagtail.fields.RichTextField(blank=True)),
                ("related_links", cms.core.fields.StreamField(blank=True, block_lookup={})),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
