# Generated by Django 5.2.10 on 2026-01-28 22:01

from django.db import migrations


def delete_pages(apps, schema_editor):
    Page = apps.get_model("wagtailcore", "Page")

    InformationPage = apps.get_model("standard_pages", "InformationPage")
    IndexPage = apps.get_model("standard_pages", "IndexPage")

    # Collect IDs of pages to delete (as core Page ids)
    info_ids = InformationPage.objects.values_list("page_ptr_id", flat=True)
    index_ids = IndexPage.objects.values_list("page_ptr_id", flat=True)

    ids_to_delete = list(info_ids) + list(index_ids)
    if not ids_to_delete:
        return

    # Deleting the wagtailcore.Page rows will cascade to:
    # - the specific page tables (standard_pages_informationpage, etc.)
    # - revisions, log entries (depending on your DB constraints), etc.
    #
    # Important: order doesn't matter much, but deleting children first is safer.
    # Wagtail stores tree structure; bulk delete at DB level can leave treebeard state weird
    # if we partially delete. We'll delete deepest pages first by path length.
    pages = Page.objects.filter(id__in=ids_to_delete).order_by("-path")

    for page in pages:
        # This uses Wagtail's deletion logic (tree + related objects)
        page.delete()


def noop_reverse(apps, schema_editor):
    # Can't restore deleted content automatically
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("standard_pages", "0003_cookiespage"),
    ]

    operations = [
        migrations.RunPython(delete_pages, reverse_code=noop_reverse),
    ]
