# Generated by Django 5.2.10 on 2026-01-28 22:01

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def delete_pages(apps, schema_editor):
    Page = apps.get_model("wagtailcore", "Page")

    InformationPage = apps.get_model("standard_pages", "InformationPage")
    IndexPage = apps.get_model("standard_pages", "IndexPage")

    # Collect IDs of pages to delete (as core Page ids)
    ids_to_delete = InformationPage.objects.values_list("page_ptr_id", flat=True).union(
        IndexPage.objects.values_list("page_ptr_id", flat=True)
    )

    if not ids_to_delete.exists():
        return

    # Collects page IDs - Gets the primary keys from both page types via page_ptr_id
    # (the foreign key to Wagtail's base Page model)
    # Orders by -path - Wagtail uses django-treebeard for page hierarchy,
    # storing tree position in a path field. Longer paths = deeper in the tree.
    # Deleting deepest first (children before parents) keeps the tree structure consistent during deletion.

    # Deletes via the base Page model - This triggers Wagtail's deletion logic, which cascades to:
    # The specific page tables (standard_pages_informationpage, etc.)
    # - Page revisions
    # - Any other related objects (search index entries, etc.)
    pages = Page.objects.filter(id__in=ids_to_delete).order_by("-path")
    deleted_count = pages.count()

    for page in pages.iterator():
        page.delete()

    logger.info("Deleted %s pages.", deleted_count)


class Migration(migrations.Migration):
    dependencies = [
        ("standard_pages", "0003_cookiespage"),
    ]

    operations = [
        migrations.RunPython(delete_pages, reverse_code=migrations.RunPython.noop),
    ]
