# Generated by Django 5.2.6 on 2025-09-30 14:10

from django.db import migrations


def create_cookies_page(apps, schema_editor):
    Page = apps.get_model("wagtailcore.Page")
    CookiesPage = apps.get_model("standard_pages.CookiesPage")
    homepage = Page.objects.get(slug="home")

    homepage.add_child(
        instance=CookiesPage(
            title="Cookies",
            slug="cookies",
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("standard_pages", "0003_cookiespage"),
    ]

    operations = [migrations.RunPython(create_cookies_page, migrations.RunPython.noop)]
