# Generated by Django 5.2.6 on 2025-09-30 14:10

from django.db import migrations
from django.utils import timezone


def create_cookies_page(apps, schema_editor):
    # Get models
    ContentType = apps.get_model("contenttypes.ContentType")
    CookiesPage = apps.get_model("standard_pages.CookiesPage")
    HomePage = apps.get_model("home.HomePage")
    Locale = apps.get_model("wagtailcore.Locale")

    # Create content type for the model
    cookies_page_type, _created = ContentType.objects.get_or_create(model="cookiespage", app_label="standard_pages")

    home_page = HomePage.objects.get(locale=Locale.objects.get(language_code="en-gb"), slug="home")

    now = timezone.now()

    # Create the English cookies page
    cookies_page = CookiesPage.objects.create(
        title="Cookies",
        draft_title="Cookies",
        live=True,
        first_published_at=now,
        last_published_at=now,
        slug="cookies",
        path=f"{home_page.path}00{home_page.numchild + 1:02d}",
        content_type=cookies_page_type,
        depth=home_page.depth + 1,
        url_path=f"{home_page.url_path}cookies/",
        locale=Locale.objects.get(language_code="en-gb"),
    )

    home_page.numchild += 1
    home_page.save()

    # TODO: use the actual welsh homepage,
    #       this can be updated once the welsh homepage is being created programmatically in migrations
    # home_page_cy = HomePage.objects.get(locale=Locale.objects.get(language_code="cy"))
    home_page_cy = home_page

    # Create the Welsh translation alias cookies page
    CookiesPage.objects.create(
        title="Cookies",
        draft_title="Cookies",
        live=True,
        first_published_at=now,
        last_published_at=now,
        slug="cycookies",  # TODO change back to "cookies"
        path=f"{home_page_cy.path}00{home_page_cy.numchild + 1:02d}",
        content_type=cookies_page_type,
        depth=home_page.depth + 1,
        url_path=f"{home_page_cy.url_path}cycookies/",  # TODO change back to "cookies"
        locale=Locale.objects.get(language_code="cy"),
        alias_of=cookies_page,
        translation_key=cookies_page.translation_key,
    )

    home_page_cy.numchild += 1
    home_page_cy.save()


class Migration(migrations.Migration):
    dependencies = [
        ("standard_pages", "0003_cookiespage"),
    ]

    operations = [migrations.RunPython(create_cookies_page, migrations.RunPython.noop)]
