# Generated by Django 5.2.10 on 2026-01-28 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("standard_pages", "0004_delete_info_and_index_pages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexpage",
            name="content",
        ),
        migrations.RemoveField(
            model_name="indexpage",
            name="featured_items",
        ),
        migrations.RemoveField(
            model_name="indexpage",
            name="related_links",
        ),
        migrations.RemoveField(
            model_name="informationpage",
            name="last_updated",
        ),
    ]
