---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: alpine
    tag: 3.23.3-does-not-exist
    registry_mirror:
      host: ((ecr_repository_uri))
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))
    aws_region: ((aws_region))

inputs:
  - name: pull_request

outputs:
  - name: build

run:
  path: pull_request/ci/scripts/build.sh
