# Generated by Django 5.1.5 on 2025-01-29 08:20

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0002_alter_topic_id_genericpagetotaxonomytopic"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExclusivePageToTaxonomyTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="genericpagetotaxonomytopic",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="genericpagetotaxonomytopic",
            constraint=models.UniqueConstraint(fields=("page", "topic"), name="unique_generic_taxonomy"),
        ),
        migrations.AddField(
            model_name="exclusivepagetotaxonomytopic",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exclusive_topic",
                to="wagtailcore.page",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="exclusivepagetotaxonomytopic",
            name="topic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="exclusive_page", to="taxonomy.topic"
            ),
        ),
    ]
