# Generated by Django 5.1.5 on 2025-01-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0002_alter_topic_id_genericpagetotaxonomytopic"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="genericpagetotaxonomytopic",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="genericpagetotaxonomytopic",
            constraint=models.UniqueConstraint(fields=("page", "topic"), name="unique_generic_taxonomy"),
        ),
    ]
