# Generated by Django 6.0.8 on 2026-09-14 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0003_topic_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpagetotaxonomytopic",
            name="topic",
            field=models.ForeignKey(
                limit_choices_to={"depth__gt": 1},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_pages",
                to="taxonomy.topic",
            ),
        ),
    ]
