# Generated by Django 5.1.6 on 2025-02-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0003_alter_genericpagetotaxonomytopic_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericpagetotaxonomytopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="related_pages", to="taxonomy.topic"
            ),
        ),
    ]
