# Generated by Django 5.1.4 on 2025-01-08 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisseries",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="AnalysisPage",
        ),
        migrations.DeleteModel(
            name="AnalysisSeries",
        ),
    ]
