# Generated by Django 5.1.7 on 2024-03-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="teams",
            field=models.ManyToManyField(blank=True, related_name="users", to="teams.team"),
        ),
    ]
