# Generated by Django 5.1.7 on 2025-03-12 12:33
# Edited as per: https://docs.djangoproject.com/en/5.1/howto/writing-migrations/#migrations-that-add-unique-fields


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
