# Generated by Django 5.2.3 on 2025-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="external_user_id",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
