# Generated by Django 5.1.7 on 2025-03-12 12:34
# Edited as per: https://docs.djangoproject.com/en/5.1/howto/writing-migrations/#migrations-that-add-unique-fields

import uuid

from django.db import migrations


def generate_uuids(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.filter(external_user_id__isnull=True):
        user.external_user_id = uuid.uuid4()
        user.save(update_fields=["external_user_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_add_external_user_id"),
    ]

    operations = [
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),
    ]
