# Generated by Django 5.1.7 on 2025-03-12 12:34
# Edited as per: https://docs.djangoproject.com/en/5.1/howto/writing-migrations/#migrations-that-add-unique-fields

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_populate_external_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="external_user_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
