services:
  web:
    extends:
      file: ../docker-compose.yml
      service: web
    build:
      context: ..
      target: dev
    environment:
      DJANGO_SETTINGS_MODULE: cms.settings.functional_test
      REDIS_URL: redis://redis
    ports: !override
      - 18000:8000 # runserver
    volumes:
      # Mount the repo at /app/
      - ../:/app/
    command:
      > # Ensure dependencies and static files are ready from inside the container, as there can be issues relying on these being run outside in the local environment
      sh -c "poetry install &&
             django-admin collectstatic --verbosity 0 --noinput --clear &&
             django-admin compilemessages --verbosity 0 &&
             django-admin locked_migrate &&
             django-admin runserver 0.0.0.0:8000"

  db:
    extends:
      file: docker-compose.yml
      service: db
    ports: !override
      - '15432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q']
      interval: 2s
      timeout: 5s
      retries: 30

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    ports: !override
      - '16379:6379'
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 2s
      timeout: 5s
      retries: 30

  broker:
    extends:
      file: docker-compose.yml
      service: broker
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092,EXTERNAL://localhost:19094'
    ports: !override
      - '19094:9094'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          '/opt/bitnami/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9094',
        ]
      interval: 5s
      timeout: 20s
      retries: 20

volumes:
  node_modules:
  pgdata:
