services:
  db:
    extends:
      file: ../docker-compose-dev.yml
      service: db
    ports: !override
      - '15432:5432'

  redis:
    extends:
      file: ../docker-compose-dev.yml
      service: redis
    ports: !override
      - '16379:6379'

  broker:
    extends:
      file: ../docker-compose-dev.yml
      service: broker
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092,EXTERNAL://localhost:19094'
    ports: !override
      - '19094:9094'

volumes:
  pgdata:
