# Generated by Django 5.1.4 on 2025-01-08 14:44

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models

import cms.bundles.models
import cms.core.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_contactdetails_core_contactdetails_name_unique"),
        ("images", "0002_customimage_description"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSeries",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="StatisticalArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("listing_title", models.CharField(blank=True, max_length=255)),
                ("listing_summary", models.CharField(blank=True, max_length=255)),
                ("social_text", models.CharField(blank=True, max_length=255)),
                ("news_headline", models.CharField(blank=True, max_length=255)),
                ("summary", wagtail.fields.RichTextField()),
                ("main_points_summary", wagtail.fields.RichTextField()),
                ("release_date", models.DateField()),
                ("next_release_date", models.DateField(blank=True, null=True)),
                ("is_accredited", models.BooleanField(default=False)),
                ("is_census", models.BooleanField(default=False)),
                ("headline_figures", cms.core.fields.StreamField(blank=True, block_lookup={})),
                ("content", cms.core.fields.StreamField(block_lookup={})),
                ("show_cite_this_page", models.BooleanField(default=True)),
                (
                    "contact_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.contactdetails",
                    ),
                ),
                (
                    "listing_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(cms.bundles.models.BundledPageMixin, "wagtailcore.page", models.Model),
        ),
    ]
