# Generated by Django 5.1.6 on 2025-02-20 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
        ("images", "0004_alter_customimage__privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleseriespage",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="articleseriespage",
            name="listing_summary",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="articleseriespage",
            name="listing_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="articleseriespage",
            name="social_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="articleseriespage",
            name="social_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
