# Generated by Django 5.1.7 on 2025-03-18 14:05

from django.db import migrations

import cms.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_articleseriespage_listing_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticalarticlepage",
            name="updates",
            field=cms.core.fields.StreamField(blank=True, block_lookup={}),
        ),
    ]
