# Generated by Django 5.1.8 on 2025-04-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_statisticalarticlepage_corrections_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticalarticlepage",
            name="headline_figures_figure_ids",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
