# Generated by Django 5.2.3 on 2025-06-24 10:35

from django.db import migrations

import cms.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_statisticalarticlepage_dataset_sorting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticalarticlepage",
            name="featured_chart",
            field=cms.core.fields.StreamField(blank=True, block_lookup={}),
        ),
    ]
