# Generated by Django 5.2.3 on 2025-06-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0008_articlesindexpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticalarticlepage",
            name="standalone_article",
            field=models.BooleanField(default=False),
        ),
    ]
