# Generated by Django 5.1.3 on 2024-11-23 17:59

import django.db.models.deletion
from django.db import migrations, models

import cms.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('highlights', cms.core.fields.StreamField(blank=True, block_lookup={})),
                ('columns', cms.core.fields.StreamField(blank=True, block_lookup={})),
            ],
            options={
                'verbose_name': 'Main Menu',
                'verbose_name_plural': 'Main Menus',
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('main_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='navigation.mainmenu')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Navigation Settings',
                'verbose_name_plural': 'Navigation Settings',
            },
        ),
    ]
