# Generated by Django 5.1.7 on 2025-04-02 12:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navigation", "0002_footermenu_navigationsettings_footer_menu"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="footermenu",
            name="locale",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footermenu",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="mainmenu",
            name="locale",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mainmenu",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="footermenu",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="mainmenu",
            unique_together={("translation_key", "locale")},
        ),
    ]
